# Dominios
DOMAIN_PROFILES = 'Profiles'

# Secciones
SECTION_CONFIG = 'Config'
SECTION_PRIORITY = 'Priority'
SECTION_IGNORE_FILES = 'IgnoreFiles'
SECTION_IGNORE_MODS = 'IgnoreMods'
SECTION_INCLUDE_MODS = 'IncludeMods'
SECTION_EXCLUSIVE_MODS = 'ExclusiveMods'
PROFILE_SECTIONS = (
    SECTION_CONFIG, SECTION_PRIORITY, SECTION_IGNORE_FILES, SECTION_IGNORE_MODS,
    SECTION_INCLUDE_MODS, SECTION_EXCLUSIVE_MODS
)

# Parametros
IGNORE_ALL_MODS_PARAMETER = "IgnoreAllMods"
EXCLUDE_ALL_MODS_PARAMETER = "ExcludeAllMods"
PARENTS_PARAMETER = "Parents"

PROFILE_CONFIG_PARAMETERS = [
    IGNORE_ALL_MODS_PARAMETER, EXCLUDE_ALL_MODS_PARAMETER, PARENTS_PARAMETER
]

# Default y limites
DEFAULT_PRIORITY = 50
DEFAULT_PROFILE = 'Default'
EMPTY_VALUE = '$None'

# Limites
MAX_PRIORITY = 100
